export const tableColumnData = [
  {
    id: "column1",
    title: "조사 대상자 번호",
    columnKey: "id",
    type: "text" as const,
    width: "20",
  },
  {
    id: "column2",
    title: "상태",
    columnKey: "status",
    type: "text"as const,
    width: "15",
  },
  {
    id: "column3",
    title: "미해결된 메뉴얼 쿼리",
    columnKey: "menualQuery",
    type: "text"as const,
    width: "20",
  },
  {
    id: "column4",
    title: "미해결된 시스템 쿼리",
    columnKey: "systemQuery",
    type: "text"as const,
    width: "20",
  },
  {
    id: "column5",
    title: "검증",
    columnKey: "validation",
    type: "checkbox"as const,
    width: "10",
  },
  {
    id: "column6",
    title: "서명",
    columnKey: "sign",
    type: "checkbox"as const,
    width: "10",
  },
  {
    id: "column7",
    title: "잠금",
    columnKey: "lock",
    type: "checkbox"as const,
    width: "10",
  },
];

export const tableData = [
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
  {
    id: "999-011",
    status: "신규",
    menualQuery: "0",
    systemQuery: "0",
    validation: false,
    sign: true,
    lock: false,
  },
];
